### ISSUE TITLE
Generated CSV doesn't load directly in Excel

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/icepirate#11]
The CSV generated by icepirate doesn't load well in Excell by default. Excel users need to use the Import... wizard. It seems tweaking the format (possibly using the python csv module) so it's more acceptable to the world's most popular spreadsheet program might be worth doing. :-)

**Comment by helgihg** [comment]
CSV will soon be removed to prevent the risk of member database leaks. This was decided in the spirit of GDPR (General Data Protection Regulation) compliance.
