### ISSUE TITLE
Reject link in emails

### ISSUE THREAD

**Issue by baldurjonsson** [piratar/icepirate#13]
Hello there!
The unsubscribe link is so long it messes up the default font size on Windows Phone 10.
Simplest solution would be to make a shorter url or better yet, use HTML emails. :)

![image](https://cloud.githubusercontent.com/assets/3398226/17006179/7c158e26-4ece-11e6-8205-6c5c2ab012a0.png)

**Comment by BjarniRunar** [comment]
A potential fix is in PR #15... a simple URL shortener ;-)

**Comment by baldurjonsson** [comment]
Looks good with the new short links. :)
